name: menu_advisor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter_credit_card: ^2.0.0
  http: ^0.13.3
  fluttertoast: ^8.0.8
  socket_io_client: ^1.0.1
  page_transition: ^2.0.2
  shared_preferences: ^2.0.7
  simple_animations: ^3.1.1
  # supercharged: ^2.0.0
  provider: ^6.0.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  # flutter_map: ^0.10.1+1
  google_maps_flutter: ^2.0.9
  flutter_polyline_points: ^1.0.0
  # latlong: ^0.6.1
  geolocator: ^7.6.1
  font_awesome_flutter: ^9.1.0
  qr_code_scanner: ^0.5.2
  # qrcode: ^1.0.4
  qr_code_tools: ^0.0.7
  stripe_payment: ^1.1.4
  # stripe_payment:
  #   git:
  #     url: git://github.com/mandreshope/flutter_stripe_payment.git
  #     ref: "8a6002631f8a00f45efdc0581744af7931583886"
  scrollable_positioned_list: ^0.1.10
  image_picker: ^0.8.4+1
  pdf: ^3.6.0
  path_provider: ^2.0.3
  permission_handler: ^8.1.6
  chips_choice: ^2.0.1
  flag: ^5.0.1
  mlkit_translate: ^1.0.0+1
  # firebase_mlkit_language: ^1.1.3
  # firebase_mlkit_language:
  #   git:
  #     url: git://github.com/mandreshope/firebase_mlkit_language.git
  #     ref: "136b4b1a12b803092fbd8e6be3a797b96b33c4b1"
  url_launcher: ^6.0.10
  flutter_html:
  # wave_slider: ^0.2.0
  flutter_balloon_slider: ^0.1.1
  # firebase_auth: ^0.18.3+1
  firebase_core: ^1.6.0
  map_launcher: ^2.1.1
  share: ^2.0.4
  pinput: ^1.2.0
  # copyable: ^0.0.1+2
  # flutter_rounded_date_picker: ^2.0.2
  # flutter_cupertino_datetime_picker: ^2.0.1
  # sortedmap: ^0.4.2+1
  material_segmented_control: ^3.1.2
  flutter_collapse: ^0.1.1
  # segment_control: ^0.1.0
  scroll_to_index: ^2.0.0
  dotted_line: ^2.0.2
  floatingpanel: ^1.1.3
  # google_map_location_picker: ^4.1.6
  place_picker: ^0.9.18
  photo_view: ^0.12.0
  responsive_framework: ^0.1.4
  geocoding: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  auto_size_text: ^2.1.0
  # geocoder: ^0.2.1
  # dialog_spinner: ^0.1.3
  carousel_slider: ^4.0.0
  firebase_analytics: ^8.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - lang/

  fonts:
    - family: Golden Ranger
      fonts:
        - asset: assets/fonts/Golden-Ranger.ttf
    - family: Soft Elegance
      fonts:
        - asset: assets/fonts/Soft-Elegance.ttf
    - family: Cool Sans
      fonts:
        - asset: assets/fonts/Cool-Sans.ttf
