name: menu_advisor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.22.2+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  flutter_credit_card: ^3.0.1
  http: ^0.13.4
  fluttertoast: ^8.0.8
  socket_io_client: ^1.0.2
  page_transition: ^2.0.4
  shared_preferences: ^2.0.11
  simple_animations: ^4.0.1
  provider: ^6.0.1
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.0.1
  font_awesome_flutter: ^9.2.0
  qr_code_scanner: ^1.0.0-alpha.1
  # qr_code_tools: ^0.0.7
  flutter_stripe: ^2.0.2
  pay: ^1.0.6
  scrollable_positioned_list: ^0.2.3
  image_picker: ^0.8.4+4
  pdf: ^3.6.5
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  chips_choice: ^2.0.1
  flag: ^5.0.1
  mlkit_translate: ^1.0.0+1
  url_launcher: ^6.0.17
  #flutter_html: ^2.1.5 #Dependencies: webview_flutter build ios fail
  flutter_balloon_slider: ^0.1.1
  firebase_core: ^1.10.6
  map_launcher: ^2.1.1
  share: ^2.0.4
  pinput: ^1.2.2
  material_segmented_control: ^3.1.2
  expandable: ^5.0.1
  scroll_to_index: ^2.1.1
  dotted_line: ^3.1.0
  floatingpanel: ^1.1.3
  place_picker: ^0.9.19-nullsafety
  photo_view: ^0.13.0
  responsive_framework: ^0.1.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  sliding_up_panel: ^2.0.0+1
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0
  firebase_analytics: ^8.3.4
  intl_phone_number_input: ^0.7.0+2
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/icon.png"

dependency_overrides:
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - lang/

  fonts:
    - family: Golden Ranger
      fonts:
        - asset: assets/fonts/Golden-Ranger.ttf
    - family: Soft Elegance
      fonts:
        - asset: assets/fonts/Soft-Elegance.ttf
    - family: Cool Sans
      fonts:
        - asset: assets/fonts/Cool-Sans.ttf
